---
title: " **[SOLAR]** STGCN Ver1 (data2, -N +S) 시뮬레이션(epoch, filter, lag)" 
author: "JiyunLim"
date: "04/29/2023"
categories:
  - Research
  - STGCN
  - SOLAR
---

# STGCN Ver1

> 50 에폭 // 완료! (csv로 저장)

> 100 에폭 // 완료!

> 150 에폭 시작 (2023-05-05-오후1시54분) // 완료!

***10 iter 완료!!***

> 150 에폭 시작(2023-05-07 오후2시 38분 시작) // 완료! (5월 9일 오전 10시5분) -- 50epoch 해야함

> 100 에폭 시작(2023-05-09 오전 10시 46분 시작) // 완료 (5월 10일 정오)

> 50에폭 시작(2023-05-10 오후 11시 10분 시작) // 완료 (5월 11일 오후 1시 36분)

**20 iter 완료!!**

> 50 에폭 시작(2023-05-11 오후 4시 40분 시작) // 완료 (5월 12일 오전 7시)

> 100 에폭 시작(2023-05-12 오전 9시 20분 시작) // 완료 (5월 13일 오후 2시 30분)

> 150 에폭 시작 (2023-05-14 오전 2시 30분 시작) // 완료 (5월 15일 오후 4시 37분)

**30 iter 완료!!**

*240개 한꺼번에 저장된 파일(second/stgcn_v1_150epoch_2) -- 2iteration*

## ref
- <https://github.com/miruetoto/yechan3/tree/main/posts/3_Researches/ITSTGCN/itstgcn>
- <https://miruetoto.github.io/yechan3/posts/3_Researches/ITSTGCN/2023-03-18-SimulationPlanner-Tutorial.html#plnr_gnar_block>

## 2022/06/01 ~ 2022/09/15

- train 2022-06-01 00:00:00 ~ 2022-08-14 17:00:00
- test 2022-08-14 18:00:00 ~ 2022-09-15 23:00:00

# import

In [6]:
import eptstgcn
import torch
import eptstgcn.planner

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

# Read Data

In [2]:
url = "https://raw.githubusercontent.com/pinkocto/noteda/main/posts/SOLAR/data2/stgcn_data1.json"
loader = eptstgcn.DatasetLoader(url)
# dataset = loader.get_dataset(lags=4)
# train_dataset, test_dataset = eptstgcn.utils.temporal_signal_split(dataset, train_ratio = 0.7)

# Simulation

## 50 epoch
- 10iter (끝)
- 20iter (on going)

In [3]:
plans_stgcn = {
    'max_iteration': 10, # 30 
    'method': ['STGCN'], 
    'lags': [4, 8, 12, 24], 
    'nof_filters': [16, 32, 64], 
    'epoch': [50] # [50, 100, 150]
}

In [4]:
plnr = eptstgcn.planner.PLNR_STGCN(plans_stgcn,loader,dataset_name='data2')

In [7]:
plans_stgcn

{'max_iteration': 10,
 'method': ['STGCN'],
 'lags': [4, 8, 12, 24],
 'nof_filters': [16, 32, 64],
 'epoch': [50]}

In [ ]:
plnr.simulate()
eptstgcn.save_data(plnr,'./simul_model2/stgcn_v1/stgcn_v1_50epoch_3.pickle')
simul_model_50 = eptstgcn.load_data('./simul_model2/stgcn_v1/stgcn_v1_50epoch_3.pickle')

1/10 is done

In [7]:
simul_model_50.simulation_results

,dataset,method,normal,lags,nof_filters,epoch,mse(train),mse(test),calculation_time
0,data2,STGCN,X,4,16,50,0.183498,0.169735,550.123783
1,data2,STGCN,X,4,32,50,0.182225,0.162033,543.581154
2,data2,STGCN,X,4,64,50,0.183565,0.171925,419.522592
3,data2,STGCN,X,8,16,50,0.19624,0.173633,415.247636
4,data2,STGCN,X,8,32,50,0.197571,0.171606,422.306532
...,...,...,...,...,...,...,...,...,...
115,data2,STGCN,X,12,32,50,0.19375,0.168965,428.73169
116,data2,STGCN,X,12,64,50,0.19339,0.169359,443.226369
117,data2,STGCN,X,24,16,50,0.226857,0.209055,398.531218
118,data2,STGCN,X,24,32,50,0.257455,0.216844,404.345611
119,data2,STGCN,X,24,64,50,0.226526,0.194404,413.1882

### 5월 11일 50에폭 3번째 이터레이션 돌리기 시작

In [8]:
simul_model_50.simulation_results

,dataset,method,normal,lags,nof_filters,epoch,mse(train),mse(test),calculation_time
0,data2,STGCN,X,4,16,50,0.177073,0.158718,317.86064
1,data2,STGCN,X,4,32,50,0.188271,0.173996,546.640334
2,data2,STGCN,X,4,64,50,0.183843,0.168644,473.151267
3,data2,STGCN,X,8,16,50,0.192224,0.169199,417.013636
4,data2,STGCN,X,8,32,50,0.193763,0.177408,422.140082
...,...,...,...,...,...,...,...,...,...
115,data2,STGCN,X,12,32,50,0.209933,0.182817,433.280491
116,data2,STGCN,X,12,64,50,0.204477,0.178089,450.442147
117,data2,STGCN,X,24,16,50,0.214642,0.190434,400.357081
118,data2,STGCN,X,24,32,50,0.25557,0.208072,410.695924
119,data2,STGCN,X,24,64,50,0.353404,0.279463,558.969701

In [ ]:
simul_model_50.simulation_results

In [28]:
plans_stgcn

{'max_iteration': 10,
 'method': ['STGCN'],
 'lags': [4, 8, 12, 24],
 'nof_filters': [16, 32, 64],
 'epoch': [150]}

In [43]:
simul_model_50.simulation_results['calculation_time'].mean()

1186.3822703550259

In [ ]:
print('stgcn ver1 50epoch 시뮬레이션 끝!')

- 첫번째 10iter m저장X (csv로만)
- Dropbox/noteda/posts/SOLAR/simulation_results/2023-05-04_04-21-58.csv

In [ ]:
import matplotlib.pyplot as plt
plt.boxplot(simul_model_50.simulation_results['mse(test)'])
plt.show()

## 100 epoch

In [3]:
plans_stgcn = {
    'max_iteration': 10, # 30 
    'method': ['STGCN'], 
    'lags': [4, 8, 12, 24], 
    'nof_filters': [16, 32, 64], 
    'epoch': [100] # [50, 100, 150]
}

In [4]:
plans_stgcn

{'max_iteration': 10,
 'method': ['STGCN'],
 'lags': [4, 8, 12, 24],
 'nof_filters': [16, 32, 64],
 'epoch': [100]}

In [5]:
plnr = eptstgcn.planner.PLNR_STGCN(plans_stgcn,loader,dataset_name='data2')

In [ ]:
plnr.simulate()
eptstgcn.save_data(plnr, './simul_model2/stgcn_v1/stgcn_v1_100epoch_3.pickle')
simul_model_100 = eptstgcn.load_data('./simul_model2/stgcn_v1/stgcn_v1_100epoch_3.pickle')

1/10 is done
2/10 is done

In [9]:
simul_model_100.simulation_results

,dataset,method,normal,lags,nof_filters,epoch,mse(train),mse(test),calculation_time
0,data2,STGCN,X,4,16,100,0.183406,0.169097,601.416962
1,data2,STGCN,X,4,32,100,0.179978,0.161778,687.800131
2,data2,STGCN,X,4,64,100,0.180906,0.164964,844.361361
3,data2,STGCN,X,8,16,100,0.196384,0.169631,828.892196
4,data2,STGCN,X,8,32,100,0.197595,0.174515,957.064054
...,...,...,...,...,...,...,...,...,...
115,data2,STGCN,X,12,32,100,0.19678,0.172842,649.31667
116,data2,STGCN,X,12,64,100,0.207231,0.178266,657.416144
117,data2,STGCN,X,24,16,100,0.251782,0.208191,588.360123
118,data2,STGCN,X,24,32,100,0.257983,0.220628,599.18159
119,data2,STGCN,X,24,64,100,0.260816,0.224017,629.292965

In [15]:
simul_model_100.simulation_results

,dataset,method,normal,lags,nof_filters,epoch,mse(train),mse(test),calculation_time
0,data2,STGCN,X,4,16,100,0.195067,0.180725,594.303679
1,data2,STGCN,X,4,32,100,0.181248,0.16525,611.907454
2,data2,STGCN,X,4,64,100,0.183541,0.165472,629.378186
3,data2,STGCN,X,8,16,100,0.201609,0.180656,616.519384
4,data2,STGCN,X,8,32,100,0.191182,0.17075,625.537024
...,...,...,...,...,...,...,...,...,...
115,data2,STGCN,X,12,32,100,0.208179,0.181665,863.704366
116,data2,STGCN,X,12,64,100,0.192994,0.168374,894.694965
117,data2,STGCN,X,24,16,100,0.226653,0.203374,797.021305
118,data2,STGCN,X,24,32,100,0.25733,0.219492,805.615929
119,data2,STGCN,X,24,64,100,0.218003,0.196679,842.991321

- 여기까지 완료!

In [ ]:
# eptstgcn.save_data(plnr, './simul_model2/stgcn_v1/stgcn_v1_100epoch.pickle')

In [ ]:
# simul_model_100 = eptstgcn.load_data('./simul_model2/stgcn_v1/stgcn_v1_100epoch.pickle')

## 150 epoch

In [16]:
plans_stgcn = {
    'max_iteration': 10, # 30 
    'method': ['STGCN'], 
    'lags': [4, 8, 12, 24], 
    'nof_filters': [16, 32, 64], 
    'epoch': [150] # [50, 100, 150]
}

In [17]:
plnr = eptstgcn.planner.PLNR_STGCN(plans_stgcn,loader,dataset_name='data2')

In [ ]:
plnr.simulate()
eptstgcn.save_data(plnr,'./simul_model2/stgcn_v1/stgcn_v1_150epoch.pickle')
simul_model_150 = eptstgcn.load_data('./simul_model2/stgcn_v1/stgcn_v1_150epoch.pickle')

In [ ]:
eptstgcn.save_data(plnr,'./simul_model2/stgcn_v1/stgcn_v1_150epoch.pickle')

In [ ]:
simul_model_150 = eptstgcn.load_data('./simul_model2/stgcn_v1/stgcn_v1_150epoch.pickle')

In [13]:
simul_model_150 = eptstgcn.load_data('./simul_model2/stgcn_v1/second/stgcn_v1_150epoch_2.pickle')

In [14]:
simul_model_150.simulation_results

,dataset,method,normal,lags,nof_filters,epoch,mse(train),mse(test),calculation_time
0,data2,STGCN,X,4,16,150,0.186116,0.165823,1221.462088
1,data2,STGCN,X,4,32,150,0.185565,0.171283,1237.214506
2,data2,STGCN,X,4,64,150,0.200393,0.186591,1497.534026
3,data2,STGCN,X,8,16,150,0.198985,0.172985,1041.296445
4,data2,STGCN,X,8,32,150,0.201762,0.175557,948.47674
...,...,...,...,...,...,...,...,...,...
235,data2,STGCN,X,12,32,150,0.189189,0.168207,1310.145853
236,data2,STGCN,X,12,64,150,0.193969,0.176804,1346.117926
237,data2,STGCN,X,24,16,150,0.220608,0.190391,1204.447807
238,data2,STGCN,X,24,32,150,0.248845,0.21056,1234.316041
239,data2,STGCN,X,24,64,150,0.216271,0.191787,1002.52125

240개 한꺼번에 저장된 파일(second/stgcn_v1_150epoch_2) -- 2iteration